version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      # Group everything except major version updates
      # and security vulnerabilities together
      regular-updates:
        update-types:
          - 'minor'
          - 'patch'
      # Must be updated together
      react:
        patterns:
          - 'react'
          - 'react-dom'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
