name: Test and lint

on:
  push:
    branches:
      - main
      - 1.x
  pull_request:
    branches:
      - main
      - 1.x

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]
        react-version: [18, 19]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Install react version
        run: npm install react@^${{ matrix.react-version }} react-dom@^${{ matrix.react-version }}
      - name: Run eslint
        run: npm run lint
      - name: Run tests
        run: npm test
